### ISSUE TITLE
utils.pyx AttributeError: 'generator' object has no attribute 'next'

### ISSUE THREAD

**Issue by emmercm** [nitmir/btdht#3]
I'm getting this error with Python 3.5.2 and btdht 0.3.1:

```
Traceback (most recent call last):
  ...
  File "...", line 6, in <module>
    dht.start()
  File "btdht/dht.pyx", line 379, in btdht.dht.DHT_BASE.start (btdht/dht.c:7806)
    self._scheduler.add_dht(self)
  File "btdht/utils.pyx", line 917, in btdht.utils.Scheduler.add_dht (btdht/utils.c:17508)
    self.add_thread(name, function, user=user)
  File "btdht/utils.pyx", line 846, in btdht.utils.Scheduler.add_thread (btdht/utils.c:15984)
    typ = iterator.next()
AttributeError: 'generator' object has no attribute 'next'

Process finished with exit code 1
```

Script is nearly empty:
```python
#!/usr/bin/env python3

import btdht
import binascii
dht = btdht.DHT()
dht.start()
```

**Comment by nitmir** [comment]
Ok, the `next` method on iterator, is moved to `__next__` in python 3.  	a27c7f5 should fix this.

**Comment by traut** [comment]
since the latest release is broken in python3 because of this issue, could you please make a new release of btdht?

**Comment by jmaris** [comment]
still appear to be having this issue, it appears that commit was also never pulled ?

**Comment by nitmir** [comment]
Sorry it took so long to publish the fixed version (from the dev branch), I have been very busy lately.
